version: "3"
services:
  proto:
    build:
      context: .
      dockerfile: docker/proto/Dockerfile
    volumes:
      - ./proto:/tmp/proto
      - ./server/proto:/tmp/proto/server
      - ./client/src/proto:/tmp/proto/client
  envoy:
    build:
      context: ./docker/envoy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - app
  app:
    command: ["go", "run", "main.go"]
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: app
    tty: true
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: sysdes
      DB_PASSWORD: sysdes
      DB_NAME: sysdes_todolist_db
    volumes:
      - ./server:/go/src/app
    ports:
      - "9090:9090"
    depends_on:
      - db
      - proto
  client:
    command: ["npm", "start"]
    build:
      context: ./docker/client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    stdin_open: true
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    platform: linux/x86_64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sysdes_todolist_db
      MYSQL_USER: sysdes
      MYSQL_PASSWORD: sysdes
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql  # uncomment to keep the data
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
    - "8001:80"
    depends_on:
      - db
